"""postgresql.conf generation.

Sizing formulas are ported from PGTune's well-known public algorithm
(https://github.com/le0pard/pgtune) rather than re-derived, per the
project's own decision to reuse existing tuning knowledge instead of
guessing at new formulas. Inputs are workload type + hardware tier
(vCPU/RAM/storage) — see workloads.py and hardware.py.
"""

from app.core.hardware import HardwareTier
from app.core.workloads import Workload

_MAX_CONNECTIONS_BY_WORKLOAD = {
    "web": 200,
    "oltp": 300,
    "dw": 40,
    "mixed": 100,
    "desktop": 20,
}

_WORK_MEM_RATIO_BY_WORKLOAD = {
    "web": 1 / 4,
    "oltp": 1 / 4,
    "dw": 1 / 2,
    "mixed": 1 / 4,
    "desktop": 1 / 16,
}

_STATISTICS_TARGET_BY_WORKLOAD = {
    "dw": 500,
}

_STORAGE_COSTS = {
    "ssd": {"random_page_cost": 1.1, "effective_io_concurrency": 200},
    "hdd": {"random_page_cost": 4, "effective_io_concurrency": 2},
}


def generate_conf(workload: Workload, hardware: HardwareTier) -> dict[str, str]:
    total_mem_kb = hardware.ram_gb * 1024 * 1024
    max_connections = _MAX_CONNECTIONS_BY_WORKLOAD.get(workload.key, 100)

    shared_buffers_kb = total_mem_kb // (16 if workload.key == "desktop" else 4)

    effective_cache_kb = (
        total_mem_kb // 4 if workload.key == "desktop" else total_mem_kb * 3 // 4
    )

    maintenance_work_mem_kb = min(total_mem_kb // 16, 2 * 1024 * 1024)

    wal_buffers_kb = min(max(shared_buffers_kb * 3 // 100, 1024), 16 * 1024)

    work_mem_ratio = _WORK_MEM_RATIO_BY_WORKLOAD.get(workload.key, 1 / 4)
    work_mem_kb = max(
        int((total_mem_kb - shared_buffers_kb) * work_mem_ratio / max_connections),
        64,
    )

    storage_costs = _STORAGE_COSTS[hardware.storage]

    settings = {
        "max_connections": str(max_connections),
        "shared_buffers": f"{shared_buffers_kb}kB",
        "effective_cache_size": f"{effective_cache_kb}kB",
        "maintenance_work_mem": f"{maintenance_work_mem_kb}kB",
        "work_mem": f"{work_mem_kb}kB",
        "wal_buffers": f"{wal_buffers_kb}kB",
        "checkpoint_completion_target": "0.9",
        "default_statistics_target": str(
            _STATISTICS_TARGET_BY_WORKLOAD.get(workload.key, 100)
        ),
        "random_page_cost": str(storage_costs["random_page_cost"]),
        "effective_io_concurrency": str(storage_costs["effective_io_concurrency"]),
        "max_worker_processes": str(hardware.vcpu),
        "max_parallel_workers": str(hardware.vcpu),
        "max_parallel_workers_per_gather": str(max(hardware.vcpu // 2, 1)),
    }
    return settings


def render_conf(settings: dict[str, str]) -> str:
    lines = [
        "# Generated by pg4all — do not hand-edit, regenerate instead.",
        "",
    ]
    lines += [f"{key} = {value}" for key, value in settings.items()]
    return "\n".join(lines) + "\n"
